#!/usr/bin/env python3
"""per - Binary packer: converts any input into a LumieOS x64 module.

Usage:
    per <output> <input>
    per <output> --stdin
    per <output> -                   (read from stdin)
    per <output> --hex "48656c6c6f"
    per <output> --raw <file>        (wrap raw file into module)
    echo "Hello" | per <output> --stdin

Modes:
    (default)    Encode input as UTF-8, embed in x64 module
    --hex        Interpret input string as hex bytes
    --raw        Wrap a raw binary file into a LumieOS module
    --bin        Output raw binary (no module header)
    --asm        Output x64 assembly listing alongside binary

Output format (default): LumieOS LSH module with embedded data.
The module's code section contains a tiny x64 stub followed by
the user data bytes. When loaded, the data is accessible in memory.
"""

import struct
import sys
import os

MAGIC_LSH = 0x48534C4C   # "LLSH"

HEADER_SIZE = 64

# Minimal x64 stub: xor eax,eax; ret
# Returns 0 (success) when entry is called.
# Data follows immediately after.
STUB_BYTES = bytes([
    0x31, 0xC0,   # xor eax, eax
    0xC3,         # ret
    0x90,         # nop (padding)
])


def align_up(val, a):
    return (val + a - 1) & ~(a - 1)


def encode_input(args):
    """Parse arguments and return the raw bytes to embed."""
    if '--hex' in args:
        idx = args.index('--hex')
        if idx + 1 >= len(args):
            print("per: --hex requires a hex string argument", file=sys.stderr)
            sys.exit(1)
        hex_str = args[idx + 1].replace(' ', '').replace('0x', '').replace('\\x', '')
        try:
            return bytes.fromhex(hex_str)
        except ValueError:
            print(f"per: invalid hex string: {hex_str}", file=sys.stderr)
            sys.exit(1)

    if '--raw' in args:
        idx = args.index('--raw')
        if idx + 1 >= len(args):
            print("per: --raw requires a file path", file=sys.stderr)
            sys.exit(1)
        raw_path = args[idx + 1]
        if not os.path.isfile(raw_path):
            print(f"per: file not found: {raw_path}", file=sys.stderr)
            sys.exit(1)
        with open(raw_path, 'rb') as f:
            return f.read()

    if '--stdin' in args or ('-' in args and args.index('-') > 0):
        return sys.stdin.buffer.read()

    # Remaining positional args after output file = the input text
    return None


def build_lsh_module(data, module_name=b'per'):
    """Build a LumieOS LSH module containing the given data."""
    stub = STUB_BYTES
    code_blob = stub + data

    code_size = len(code_blob)
    entry = 0  # entry point = start of stub
    reloc_off = 0
    reloc_count = 0
    import_off = 0
    import_count = 0
    strtab_off = 0
    strtab_size = 0
    bss_size = 0

    # Build header
    name_padded = module_name[:24].ljust(24, b'\x00')
    header = struct.pack(
        '<IIIIIIIIII',
        MAGIC_LSH,
        entry,
        code_size,
        bss_size,
        reloc_off,
        reloc_count,
        import_off,
        import_count,
        strtab_off,
        strtab_size,
    )
    header += name_padded
    assert len(header) == HEADER_SIZE

    return header + code_blob


def build_raw(data):
    """Return raw binary, no wrapper."""
    return data


def build_asm_listing(data, module_name='per'):
    """Return an x64 assembly listing showing the stub + data."""
    lines = []
    lines.append(f"; Generated by per - LumieOS x64 module")
    lines.append(f"; Module: {module_name}")
    lines.append(f"; Data size: {len(data)} bytes")
    lines.append(f"; Total code size: {len(STUB_BYTES) + len(data)} bytes")
    lines.append(f"")
    lines.append(f"bits 64")
    lines.append(f"")
    lines.append(f"section .text")
    lines.append(f"global entry")
    lines.append(f"")
    lines.append(f"entry:")
    lines.append(f"    xor eax, eax        ; return 0")
    lines.append(f"    ret")
    lines.append(f"")
    lines.append(f"section .data")
    lines.append(f"global payload")
    lines.append(f"global payload_len")
    lines.append(f"")
    lines.append(f"payload:")
    # Show first bytes
    for i in range(0, min(len(data), 64), 16):
        chunk = data[i:i+16]
        hex_bytes = ', '.join(f'0x{b:02x}' for b in chunk)
        lines.append(f"    db {hex_bytes}")
    if len(data) > 64:
        lines.append(f"    ; ... ({len(data) - 64} more bytes)")
    lines.append(f"")
    lines.append(f"payload_len: dq {len(data)}")
    return '\n'.join(lines)


def main():
    if len(sys.argv) < 2:
        print(__doc__, file=sys.stderr)
        sys.exit(1)

    args = sys.argv[1:]

    # Detect flags
    raw_mode = '--bin' in args
    asm_mode = '--asm' in args

    # Filter out flags for positional arg parsing
    flag_indices = []
    for i, a in enumerate(args):
        if a.startswith('--') or a == '-':
            flag_indices.append(i)
            if a in ('--hex', '--raw') and i + 1 < len(args):
                flag_indices.append(i + 1)

    # First non-flag arg = output file
    positional = [args[i] for i in range(len(args)) if i not in flag_indices]

    if len(positional) < 1:
        print("per: missing output file argument", file=sys.stderr)
        sys.exit(1)

    output_path = positional[0]
    module_name = os.path.splitext(os.path.basename(output_path))[0].encode('ascii', errors='replace')[:24]

    # Get input data
    data = None

    if '--hex' in args:
        hex_idx = args.index('--hex')
        hex_str = args[hex_idx + 1].replace(' ', '').replace('0x', '').replace('\\x', '')
        try:
            data = bytes.fromhex(hex_str)
        except ValueError:
            print(f"per: invalid hex string: {hex_str}", file=sys.stderr)
            sys.exit(1)
    elif '--raw' in args:
        raw_idx = args.index('--raw')
        raw_path = args[raw_idx + 1]
        with open(raw_path, 'rb') as f:
            data = f.read()
    elif '--stdin' in args or (len(positional) > 1 and positional[1] == '-'):
        data = sys.stdin.buffer.read()
    elif len(positional) > 1:
        # Remaining positional args = input text
        input_text = ' '.join(positional[1:])
        data = input_text.encode('utf-8')
    else:
        # Try reading from stdin if it's not a terminal
        if not sys.stdin.isatty():
            data = sys.stdin.buffer.read()
        else:
            print("per: no input data provided", file=sys.stderr)
            print("Usage: per <output> <text>", file=sys.stderr)
            print("       per <output> --hex \"48656c6c6f\"", file=sys.stderr)
            print("       per <output> --raw <file>", file=sys.stderr)
            print("       echo 'text' | per <output> --stdin", file=sys.stderr)
            sys.exit(1)

    if data is None or len(data) == 0:
        print("per: empty input", file=sys.stderr)
        sys.exit(1)

    print(f"per: input size = {len(data)} bytes")

    # Build output
    if raw_mode:
        output = build_raw(data)
        print(f"per: mode = raw binary")
    else:
        output = build_lsh_module(data, module_name)
        print(f"per: mode = LumieOS LSH module")
        print(f"per: stub = {len(STUB_BYTES)} bytes (x64: xor eax,eax; ret)")
        print(f"per: code section = {len(output) - HEADER_SIZE} bytes")
        print(f"per: entry offset = 0x00")

    # Write output
    with open(output_path, 'wb') as f:
        f.write(output)

    print(f"per: output = {output_path} ({len(output)} bytes)")

    # Optionally emit ASM listing
    if asm_mode:
        asm_path = output_path + '.asm'
        listing = build_asm_listing(data, module_name.decode('ascii', errors='replace'))
        with open(asm_path, 'w') as f:
            f.write(listing)
        print(f"per: asm listing = {asm_path}")

    # Summary
    if not raw_mode:
        header = struct.unpack_from('<IIIIIIIIII', output, 0)
        print(f"per:")
        print(f"  magic      = 0x{header[0]:08X} (LSH)")
        print(f"  entry      = 0x{header[1]:08X}")
        print(f"  code_size  = {header[2]} (0x{header[2]:X})")
        print(f"  bss_size   = {header[3]}")
        print(f"  reloc_off  = {header[4]}")
        print(f"  reloc_cnt  = {header[5]}")
        print(f"  import_off = {header[6]}")
        print(f"  import_cnt = {header[7]}")
        print(f"  strtab_off = {header[8]}")
        print(f"  strtab_sz  = {header[9]}")
        print(f"  name       = {module_name.decode('ascii', errors='replace')}")


if __name__ == '__main__':
    main()
